### ISSUE TITLE
大佬可以教教我怎么换其他的打码平台嘛 现在用的是云码 不知道如何配置

### ISSUE THREAD

**Issue by Cxy-2008** [Womsxd/MihoyoBBSTools#141]
要先去https://www.rrocr.com注册个账号，目前有没免费额度不清楚。 当然有能力可以换其他的打码平台。然后平台上会有个token(就是平台上的 appKey )，放到配置文件里的最下面：

```
....
cloud_games:
  genshin:
    enable: false
    token: ''
#最下面新增：
captcha:
  token: xxxxxxxxxxxxxx
```

_Originally posted by @yriiolik in https://github.com/Womsxd/MihoyoBBSTools/issues/104#issuecomment-1845186293_
